name: "Terraform apply"

on:
  push:
    branches:
      - main

concurrency:
  group: terraform

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.4"

      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS }}

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
